version: '3'
services:
  strapi:
    image: strapi/strapi
    container_name: strapi_assistant
    volumes:
      - ./server:/srv/app
    ports:
      - '1337:1337'
    env_file: .env.local
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
